- name: docker build and push
  hosts: localhost
  
  tasks:
    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petshop

    - name: tag image
      command: docker tag petstore:latest mohamedmagdykhamis/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
      vars:
        docker_username: "{{ lookup('jenkins', 'dockerhub-username', 'vault://jenkins-credentials') }}"
        docker_password: "{{ lookup('jenkins', 'dockerhub-password', 'vault://jenkins-credentials') }}"

    - name: Push image
      command: docker push mohamedmagdykhamis/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 mohamedmagdykhamis/petstore:latest
